services:
  app:
    image: ghcr.io/rafik-hafri/ticketbounty/ticketbounty-app:latest
    container_name: ticketbounty-app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
      - DIRECT_URL
      - RESEND_API_KEY
    command: ["npm", "run", "start"]
    networks:
      - shared-postgres-network

networks:
  shared-postgres-network:
    external: true
