services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: ticketbounty-app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: ["npm", "run", "start"]
    networks:
      - shared-postgres-network

networks:
  shared-postgres-network:
    external: true
