version: '3.8'

services:
  # Next.js app
  app:
    build:
      context: .  
      dockerfile: Dockerfile 
    container_name: ticketbounty-app
    working_dir: /app
    ports:
      - "3000:3000" 
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: ["npm", "run", "start"]  
    
  



