services:
  app:
    image: ghcr.io/${{ github.repository }}/ticketbounty-app:latest # Pulls the pre-built image from GHCR
    container_name: ticketbounty-app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: ["npm", "run", "start"]
    networks:
      - shared-postgres-network

networks:
  shared-postgres-network:
    external: true
