import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import Header from "@/app/_navigation/header";
import Sidebar from "@/app/_navigation/sidebar/components/sidebar";
import RedirectToast from "@/components/redirect-toast";
import { ThemeProvider } from "@/components/theme/theme-provider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Notes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     
        <ThemeProvider>
          <Header/>
          <div className="flex h-screen overflow-hidden border-collapse">
             <Sidebar/>
            <main  className="
                    ml-auto
                    min-h-screen flex-1
                    overflow-y-auto overflow-x-hidden
                    py-24 px-5 md:px-8
                    bg-secondary/20
                    flex flex-col
                    
                  ">
            {children}
            </main>
          </div>
         
            <Toaster expand/>
          </ThemeProvider>
       
      </body>
      <RedirectToast/>
    </html>
  );
}
