import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import Header from "@/components/header";
import RedirectToast from "@/components/redirect-toast";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Providers } from "@/providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Notes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Providers>
        <ThemeProvider>
          <Header/>
            <main  className="
                    min-h-screen flex-1
                    overflow-y-auto overflow-x-hidden
                    py-24 px-8
                    bg-secondary/20
                    flex flex-col
                  ">
            {children}
            </main>
            <Toaster expand/>
          </ThemeProvider>
        </Providers>
      </body>
      <RedirectToast/>
    </html>
  );
}
