name: Deploy Next.js App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Build and Push Docker Image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            cd /home/rafik/ticketbounty  
            git pull origin main  
            docker-compose down  
            docker-compose up -d --build
