name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/ticketbounty-app:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/ticketbounty-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 2222
          script: |
            export NODE_ENV=production
            export INNGEST_EVENT_KEY=${{ secrets.INNGEST_EVENT_KEY}}
            export INNGEST_SIGNING_KEY=${{ secrets.INNGEST_SIGNING_KEY}}
            export INNGEST_DEV=false
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            export DIRECT_URL=${{ secrets.DATABASE_URL }}

            cd /home/rafik/ticketbounty
            git pull origin main 
            docker-compose down
            docker-compose up -d --pull always
            sleep 5 
            docker exec ticketbounty-app npx prisma migrate deploy
            docker exec ticketbounty-app npx prisma generate
          debug: true
